[build]
  command = "npm run build"
  publish = "out"

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Netlify Forms handling
[build.processing.html]
  pretty_urls = true

# Environment variables
[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://stiftelseguiden.se"