[build]
  command = "npm run build"
  publish = ".next"

# Redirect all routes to Next.js for handling
[[redirects]]
  from = "/*"
  to = "/_next/static/chunks/pages/:splat"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Netlify Forms handling
[build.processing.html]
  pretty_urls = true

# Environment variables
[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://stiftelseguiden.se"